"Couriers"
{
	"1"
	{
		"1" "npc_courier_donkey"
		"2" "npc_courier_flying_donkey"
	}
	"2"
	{
		"1" "npc_courier_mega_greevil"
		"2" "npc_courier_flying_mega_greevil"
	}
	"3"
	{
		"1" "npc_courier_pudge"
		"2" "npc_courier_flying_pudge"
	}
	"4"
	{
		"1" "npc_courier_lockjaw"
		"2" "npc_courier_flying_lockjaw"
	}
	"5"
	{
		"1" "npc_courier_arneyb_rabbit"
		"2" "npc_courier_flying_arneyb_rabbit_flying"
	}
}
